---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-devops-paradox-1
  namespace: argocd
spec:
  destination:
    namespace: pr-devops-paradox-1
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "1.71"
        ingress:
          host: "pr-devops-toolkit-1.52.44.134.120.xip.io"
      version: v3
    path: helm
    repoURL: https://github.com/vfarcic/devops-paradox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
